name: "Cross Compile Build"

on:
  push:
  pull_request:
    branches: [ main ]


jobs:
  cross-compile:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: "Build"
      run: "make tools cross_compile"

    - name: Build linux/mipsle binary
      run: |
        mkdir -p builds/pkg/linux_mipsle
        CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat GOEXPERIMENT=nofutex go build -ldflags="-s -w -extldflags=-static" -tags="netgo,osusergo" -o builds/pkg/linux_mipsle/gotty
        ls -la builds/pkg/linux_mipsle
    - name: Upload artifacts
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v7
      with:
        name: binaries
        path: builds/pkg/*/gotty